### ISSUE TITLE
Typescript definition file

### ISSUE THREAD

**Issue by mweiczorek** [MatthieuLemoine/electron-push-receiver#10]
Hi,

Not a bug or issue, quite the contrary. I implemented this into my TypeScript electron project, and since you don't have a types file, I made one:

    interface ElectronPushReceiver {
        START_NOTIFICATION_SERVICE: string;
        NOTIFICATION_SERVICE_STARTED: string;
        NOTIFICATION_SERVICE_ERROR: string;
        NOTIFICATION_RECEIVED: string;
        TOKEN_UPDATED: string;
        setup: (webContents: Electron.WebContents) => void;
    }

    declare const electronPushReceiver: ElectronPushReceiver;
    export = electronPushReceiver;

Cheers.

**Comment by MatthieuLemoine** [comment]
@mweiczorek Can you make a PR to add  this types file ?

**Comment by mweiczorek** [comment]
Yeah, I don't know how to do that for projects other than my own.

**Comment by MatthieuLemoine** [comment]
You need to fork this project. Then clone it, make your changes, commit & pull. After that, you'll see a message asking you if you want to create a pull request.

**Comment by MatthieuLemoine** [comment]
Fixed in #17.
