### ISSUE TITLE
GCM register has failed

### ISSUE THREAD

**Issue by RaimisJ** [MatthieuLemoine/electron-push-receiver#13]
Hi,

Works as expected in development. However, if I package it using electron-packager, I get this error (on ipcRenderer.send(START_NOTIFICATION_SERVICE, 'correct id'))

Register request has failed with Error=PHONE_REGISTRATION_ERROR
Retry... 1 
<retries 5 times, then>
Register request has failed with Error=PHONE_REGISTRATION_ERROR
PUSH_RECEIVER:::Error while starting the service Error: GCM register has failed

What could be the problem?

**Comment by RaimisJ** [comment]
The problem is with webpack - it does not copy .proto files and also when UglyfyJS is applied somehow the code stops working.

**Comment by victordev** [comment]
Hey @RaimisJ, how to fix this?

Thanks.

**Comment by RaimisJ** [comment]
In my case, this problem entirely depended on my configuration:
1 .In my configuration I had to swap "webpack.optimize.UglifyJsPlugin" with "uglifyjs-webpack-plugin", as the former produces unexpected results.
2. Also, my configuration produces single electron.js file while packing, but it does not bundle proto files. So I copy them myself:
  shell.cp(path.join(__dirname, '../node_modules/push-receiver/src/client/mcs.proto'), targetPath)
  shell.cp(path.join(__dirname, '../node_modules/push-receiver/src/gcm/android_checkin.proto'), targetPath)
  shell.cp(path.join(__dirname, '../node_modules/push-receiver/src/gcm/checkin.proto'), targetPath)

**Comment by victordev** [comment]
Thanks @RaimisJ

**Comment by ream88** [comment]
I'm also encountering this problem, however my `.proto` files are properly copied to my build dir.
I also works perfectly even when compiled with `webpack`, it however fails with the same error when compiling the code with `electron-build`. Any ideas?

**Comment by ream88** [comment]
@RaimisJ what is `targetPath` in your config? The output folder of webpack?

**Comment by RaimisJ** [comment]
@ream88 in the end, I ended up using not bundled node_modules folders. Only then it works correctly in all cases.

**Comment by ream88** [comment]
@RaimisJ Yeah, not using webpack and bundling the files helped! However now I need more and more features provided via webpack like for example its DefineWebpack plugin, and I'm stuck again 😞

**Comment by tom-s** [comment]
Hi have the same issue, has anybody found any solultion. I use webpack but copy the fileswith CopyWebPackPlugin when building. It works perfectly in my dev dev environment, but when i package the app with electron builder I get the infamous PHONE_REGISTRATION_ERROR. The proto files are included in the asar file and loaded correctly (I've checked putting logs in my node modules). So the problem comes from elsewhere but I can't figure it out. Any ideas ?

**Comment by MatthieuLemoine** [comment]
@ream88 I think you have the issue as #32

**Comment by benoist** [comment]
```
process.env.NODE_ENV = process.env.NODE_ENV || "production"

const CleanWebpackPlugin = require("clean-webpack-plugin")
const CopyWebpackPlugin = require("copy-webpack-plugin")

module.exports = {
  module: {
    rules: [
      {
        test: /\.(m?js|node)$/,
        parser: {amd: false},
        use: {
          loader: "@zeit/webpack-asset-relocator-loader",
          options: {
            outputAssetBase: "build",
          },
        },
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: "babel-loader",
      },
    ],
  },
  entry: "./main.js",
  plugins: [
    new CleanWebpackPlugin(["dist", "build"]),
    new CopyWebpackPlugin([
      {from: "node_modules/push-receiver/src/mcs.proto", to: "build"},
      {from: "node_modules/push-receiver/src/gcm/android_checkin.proto", to: "build"},
      {from: "node_modules/push-receiver/src/gcm/checkin.proto", to: "build"},
    ]),
  ],
  output: {
    path: __dirname,
    filename: "main-packaged.js",
  },
  node: {
    __dirname: false,
    __filename: false,
  },
  target: "electron-main",
  mode: "production",
  stats: {
    colors: true,
    children: false,
    chunks: false,
    modules: false,
  },
}
```

This works for me
