### ISSUE TITLE
Display notification using chrome's push manager.

### ISSUE THREAD

**Issue by sujitgawas19** [MatthieuLemoine/electron-push-receiver#19]
I don't want to use electron's notification api to display the notifications.
Is there any other way for displaying notification like the way chrome does??

**Comment by MatthieuLemoine** [comment]
If you dont' want to use electron, you can use [push-receiver](https://github.com/MatthieuLemoine/push-receiver) directly and handle the incoming notifications as you want from any type of processes.

**Comment by sujitgawas19** [comment]
push-receiver was built using chrome's Push manager. So can it be used to display notification the way  chrome does??

**Comment by MatthieuLemoine** [comment]
@sujitgawas19 What do you mean by "the way chrome does" ?

**Comment by omar10594** [comment]
@sujitgawas19 You can get the notification data with this library, and then you can show the notification to the user the way you want, with any library.
This library allow you to receive notifications from FCM, but you should implement the ui to show the notification.
For example you could use [node-notifier](https://github.com/mikaelbr/node-notifier)

**Comment by sujitgawas19** [comment]
@omar10594 Okay. Got It. Thank You.
