### ISSUE TITLE
Reinstalling an app that has already registered with FCM

### ISSUE THREAD

**Issue by JohannBlake** [MatthieuLemoine/electron-push-receiver#22]
If an app registers with FCM and receives a token and the client stores the token on the backend and then the user uninstalls the app and reinstalls it (or just clears the app's cache), is it possible for the client to retrieve the token from the backend and then reuse it when it attempts to register with FCM?

I assume that this is possible but only if my code would actually store the token back in the same place where it was originally stored in cache.

**Comment by JohannBlake** [comment]
After playing around with the push-receiver, it appears that you can do this.

**Comment by hieu-ht** [comment]
> After playing around with the push-receiver, it appears that you can do this.

@JohannBlake Would you have any hints or insightful guidelines to implement your idea? Thank you
