### ISSUE TITLE
ipcRenderer is undefined

### ISSUE THREAD

**Issue by Manjucloudmpower** [MatthieuLemoine/electron-push-receiver#28]
getting an error ipcRenderer is undefined on main.js

**Comment by MatthieuLemoine** [comment]
You can't use `ipcRenderer` in the main process. Only in the renderer process.

**Comment by Amethystafyy282** [comment]
@Manjucloudmpower Hi, have u been able to fix when fire says success but didn't receive anything? Thank u!

**Comment by Manjucloudmpower** [comment]
Hello, I couldn't recieve push notification when I triggered it from the firebase console but it did work when sent from backend.

**Comment by shahketul11** [comment]
Hello, I am not able to generate a token using electron-push-reciver
Please help me out
