### ISSUE TITLE
generating token but no notification

### ISSUE THREAD

**Issue by cmpDrone** [MatthieuLemoine/electron-push-receiver#29]
Tokens are being generated successfully.  Pushing notifications from firebase console using generated token and it shows as success. But not receiving any notification.

**Comment by maxfadeev** [comment]
Hi. I run into the same issue. If you have fixed that could you explain how you did that please ?

**Comment by maxfadeev** [comment]
I have just seen the explanation in the description 
> With the app running, select View -> Toggle Developer Tools. You should see the client's FCM push token in the Chromium debug console. Copy this token and paste it into the postman_collection.json (replacing "FCM_CLIENT_PUSH_TOKEN" with it). You should now be able to send yourself (or any other client registered with your Sender ID) a push message using Postman

**Comment by shahketul11** [comment]
Please explain how the token is generate using electron-push-receiver as I ain't able to get through it 
![Screenshot 2023-07-11 at 3 59 47 PM](https://github.com/MatthieuLemoine/electron-push-receiver/assets/123630563/616fd8f2-c235-41b5-9ea1-33f7873e5aab)
