### ISSUE TITLE
Receiving notifications on a destroyed window causes exception

### ISSUE THREAD

**Issue by codeminic** [MatthieuLemoine/electron-push-receiver#40]
So cool that you brought push notifications to electron! First of all, thanks for that! 

Sadly, im facing the following issue when using your library: When receiving a notification on a window that has been closed (but the app instance itself is still alive), incoming notifications are causing exceptions, probably because electron-push-receiver tries to call some method on the web contents object that has been destroyed.

![image](https://user-images.githubusercontent.com/16257869/49962048-76a8c180-ff14-11e8-964f-77e1f9bab557.png)

Is there a way around this, maybe something like a 'teardownPushReceiver' method?

Just let me know if you need some code to repro this behavior.

**Comment by achou11** [comment]
@codeminic did you happen to find a workaround for this issue?

**Comment by codeminic** [comment]
Yes, but a really poor one. I copied the relevant code from this project and surrounded the crashing parts with try-catch clauses.

**Comment by pedrobertao** [comment]
Anyone know a solution to do this ? It's happening sporadically in my project

**Comment by MatthieuLemoine** [comment]
Fixed in https://github.com/MatthieuLemoine/electron-push-receiver/releases/tag/v2.1.3

**Comment by danieltigse** [comment]
Does anybody still have the same error? I still have it
