### ISSUE TITLE
i'm not receiving the token on windows 

### ISSUE THREAD

**Issue by BluFenix00** [MatthieuLemoine/electron-push-receiver#44]
the event "notification-service-started" is not always executed on windows, but on mac the same code works fine, i am using electron 1.8.4

**Comment by shahketul11** [comment]
Cannot you please guide me as I cannot generate a token on macos
![Screenshot 2023-07-11 at 3 59 47 PM](https://github.com/MatthieuLemoine/electron-push-receiver/assets/123630563/f0e40920-7438-43da-be3f-e5c38e7f8b86)
