### ISSUE TITLE
"Connection lasted less than 1 minute" purpose?

### ISSUE THREAD

**Issue by PedroKantar** [MatthieuLemoine/electron-push-receiver#5]
Hi Matthieu,

I'm facing the "Connection lasted less than 1 minute" case:
>Connection to MCS server lost
>MCS socket closed after 0 minutes
>Connection lasted less than 1 minute
>Giving up...

Basically, if the internet connection is lost before one minute, after the connect took place, the "retry" mechanism is disabled forever and no more push notifications..

What is the purpose of this mechanism? Why could not we keep on retrying even if the connection was lost very quickly after the connect operation?

Thanks, Pedro.

**Comment by MatthieuLemoine** [comment]
Ah yeah I didn't think about that ! Nice catch !

The purpose was just to avoid infinite retry if MCS server kick the client out because of a registration issue or something like this.

**Comment by PedroKantar** [comment]
OK, I see..

**Comment by MatthieuLemoine** [comment]
Fix in v1.2.1

**Comment by PedroKantar** [comment]
Thanks for tagging as a bug, I thought I could over come this case at API level, but I did not receive any error via the `NOTIFICATION_SERVICE_ERROR` channel.
