### ISSUE TITLE
[Tag 1.2.3] package.json missing update 

### ISSUE THREAD

**Issue by PedroKantar** [MatthieuLemoine/electron-push-receiver#7]
Looks like package.json was not upated for [push_receiver](https://github.com/MatthieuLemoine/electron-push-receiver/blob/c3596db2cb3c386d8ac773c6dfb7d835bf5482bd/package.json#L11) and also the [version](https://github.com/MatthieuLemoine/electron-push-receiver/blob/c3596db2cb3c386d8ac773c6dfb7d835bf5482bd/package.json#L3).

Sorry if i missed something..
Pedro.

**Comment by MatthieuLemoine** [comment]
Yes I forgot to push my local commits !

**Comment by PedroKantar** [comment]
@MatthieuLemoine the [push_receiver](https://github.com/MatthieuLemoine/electron-push-receiver/blob/ef936d6d090e723cc0e67f73805e9702cf19a2c1/package.json#L11) dependency is still set to : "push-receiver": "^1.1.3".
It should be the [V1.1.4](https://github.com/MatthieuLemoine/push-receiver/tree/v1.1.4), no?

**Comment by MatthieuLemoine** [comment]
No that's not needed because `^1.1.3` means the latest `1.1.X`

**Comment by PedroKantar** [comment]
👌
